name: app
type: php:8.3
size: S

build:
  flavor: composer

relationships:
  database: "db:mysql"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"

mounts:
  "var": { source: "storage", source_path: "var" }
  "public/uploads": { source: "storage", source_path: "uploads" }

variables:
  env:
    APP_ENV: "prod"
    # APP_SECRET и др. зададим как переменные окружения в панели/CLI

hooks:
  build: |
    set -e
    composer install --no-dev --prefer-dist --optimize-autoloader
  deploy: |
    set -e
    php bin/console doctrine:migrations:migrate --no-interaction || true
    php bin/console cache:clear
    php bin/console assets:install
