applications:
    app:
        type: "php:8.2"

        build:
            flavor: composer

        runtime:
            extensions:
                - intl
                - opcache
                - pdo_mysql
                - sodium

        mounts:
            "/var": "shared:files/var"
            "/var/log": "shared:files/logs"
            "/public/uploads": "shared:files/uploads"

        relationships:
            database: "mysql:mysql"

        variables:
            env:
                APP_ENV: "prod"
                APP_DEBUG: "0"
                APP_SECRET: "@app.secret"

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"
                    expires: -1
                    scripts: true
                    allow: true

        hooks:
            build: |
                set -e
                cat <<EOF > .env
                APP_ENV=${APP_ENV:-prod}
                APP_DEBUG=${APP_DEBUG:-0}
                APP_SECRET=${APP_SECRET:-ChangeMePlease123456789}
                DATABASE_URL=${DATABASE_URL:-mysql://user:pass@127.0.0.1:3306/app?charset=utf8mb4}
                MAILER_DSN=${MAILER_DSN:-null://null}
                EOF
                sed -i 's/^[[:space:]]*//' .env
                composer install --no-dev --optimize-autoloader --apcu-autoloader
            deploy: |
                set -e
                php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
                php bin/console cache:clear

